apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "argo-cd-wrapper.fullname" . }}
  labels:
    {{- include "argo-cd-wrapper.labels" . | nindent 4 }}
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: ghcr.io/argoproj/argo-helm
      targetRevision: 6.7.0
      helm:
        valueFiles:
          - $values/02-argo-cd/values.yaml
    - repoURL: https://github.com/mhoyer/k3s-peng
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  revisionHistoryLimit: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
