includeApplications: true

argo-cd:
  ## ArgoCD configuration
  ## Based on: https://github.com/argoproj/argo-helm/blob/argo-cd-6.7.12/charts/argo-cd/values.yaml
  ##           https://github.com/argoproj/argo-helm/compare/argo-cd-6.7.12..main#files_bucket
  crds:
    install: true
    keep: false

  fullnameOverride: argo-cd
  global:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
    # image:
    #   repository: harbor/cache.quay.io/argoproj/argocd

  configs:
    cm:
      server.rbac.log.enforce.enable: true
      exec.enabled: false
      admin.enabled: true # !!!!
      timeout.reconciliation: 60s # default 180s
    params:
      server.insecure: true
      # server.basehref: / # see ingress config in server: section
    repositories:
      argo-helm:
        url: ghcr.io/argoproj/argo-helm
        name: argo-helm
        type: helm
        enableOCI: "true"
      external-secrets:
        url: ghcr.io/external-secrets/charts
        name: external-secrets
        type: helm
        enableOCI: "true"

  controller:
    replicas: 1
    extraArgs: [ "--kubectl-parallelism-limit", "5" ]
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8082"
    resources:
      requests: { cpu: 500m, memory: 2Gi }
      limits: { memory: 2Gi }
    metrics:
      enabled: true

  dex:
    resources:
      requests: { cpu: 10m, memory: 64Mi }
      limits: { memory: 64Mi }

  redis:
    extraArgs:
      - "--tcp-backlog"
      - "128"
      - "--bind"
      - "0.0.0.0"
      - "--maxmemory"
      - "256mb"
    resources:
      requests: { cpu: 100m, memory: 320Mi }  # see `--maxmemory` option in `extraArgs` (plus 64MB buffer)
      limits: { memory: 320Mi }               # see `--maxmemory` option in `extraArgs` (plus 64MB buffer)

  server:
    replicas: 1
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8083"
    resources:
      requests: { cpu: 100m, memory: 192Mi }
      limits: { memory: 192Mi }
    metrics:
      enabled: true
    ingress:
      enabled: true
      annotations: {}
        # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        # helm.sh/hook: post-upgrade,post-install
      hostname: "argo-cd.local"
      path: /
      pathType: Prefix
      tls: false

  ## Repo Server
  repoServer:
    replicas: 1
    extraArgs: [ "--parallelismlimit", "5" ]
    resources:
    requests: { cpu: 10m, memory: 256Mi }
    limits: { memory: 1Gi }
    metrics:
      enabled: true

    ## HACK https://github.com/argoproj/argo-cd/issues/9809#issuecomment-1298785315
    containerSecurityContext:
      seccompProfile: null
