apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mhoyer/k3s-peng
        revision: HEAD
        directories:
          - path: 03-platform-apps/*
  template:
    metadata:
      name: "{{ index .path.segments 1 }}"
    spec:
      project: "default" # TODO "platform"
      source:
        repoURL: https://github.com/mhoyer/k3s-peng
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "platform-{{ index .path.segments 1 }}"
      revisionHistoryLimit: 0
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false

      # see: https://github.com/argoproj/argo-cd/issues/9071
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers: [ "/spec/name" ] # just a HACK
          jqPathExpressions:
            - .spec.conversion.webhook.clientConfig.caBundle
            - .spec.conversion.webhook.clientConfig.service.name
            - .spec.conversion.webhook.clientConfig.service.namespace
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jsonPointers: [ "/spec/name" ] # just a HACK
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
