apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "external-secrets"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  sources:
    - chart: "external-secrets"
      repoURL: "ghcr.io/external-secrets/charts"
      targetRevision: 0.9.13
      helm:
        values: |
          ## https://github.com/external-secrets/external-secrets/blob/helm-chart-0.9.13/deploy/charts/external-secrets/values.yaml
          ## https://github.com/external-secrets/external-secrets/compare/helm-chart-0.9.14...main#files_bucket
          replicaCount: 1
          revisionHistoryLimit: 0
          # image:
          #   repository: harbor/cache.ghcr.io/external-secrets/external-secrets
          leaderElect: false
          resources:
            requests: { cpu: 10m, memory: 32Mi }
            limits: { memory: 128Mi }

          # Probably not required for our setup. See: https://github.com/external-secrets/external-secrets/issues/1270
          webhook: { create: false }
          certController: { create: false }

          deploymentAnnotations:
            reloader.stakater.com/auto: "true"

          podAnnotations:
            prometheus.io/port: "8080"
            prometheus.io/scrape: "true"
  destination:
    server: https://kubernetes.default.svc  # {{ .app.spec.destination.server }}
    namespace: "external-secrets" # {{ .app.spec.destination.namespace }}
  revisionHistoryLimit: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  # see: https://github.com/argoproj/argo-cd/issues/9071
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers: [ "/spec/name" ] # just a HACK
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
        - .spec.conversion.webhook.clientConfig.service.name
        - .spec.conversion.webhook.clientConfig.service.namespace
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers: [ "/spec/name" ] # just a HACK
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle

